theme: jekyll-theme-cayman
description: "Astro's notebook"
url: "https://daizhirui.github.io"
highlighter: rouge
show_downloads: false
github:
    is_project_page: true
    repository_url: "https://daizhirui.github.io"
    owner_url: "https://github.com/daizhirui"
    owner_name: "Zhirui Dai"
