remote-theme: jekyll-text-theme
title: "Zhirui Dai"
description: "Record my journey of science and engineering exploration"
url: "https://daizhirui.github.io"
source: "."

lange: en
license: CC-BY-NC-4.0
toc:
  selectors: "h1,h2,h3"
# Mathjax
mathjax: true
mathjax_autoNumber: true
# Mermaid
mermaid: true
# Chart
chart: true
plugins:
  - jekyll-remote-theme

highlighter: rouge
show_downloads: false
github:
    is_project_page: true
    repository_url: "https://daizhirui.github.io"
    owner_url: "https://github.com/daizhirui"
    owner_name: "Zhirui Dai"
